Fix crash in non-matching incoming IPv4 packets
Igalia/snabbswitch pull request #439
Opened 2016-09-14 15:02 UTC by dpino

Fixes https://github.com/Igalia/snabb/issues/438

The crash was happening in non-matching incoming IPv4 packets. The `transmit_icmpv4_reply` function was in charge of freeing up the original non-matching packet, but in some parts of the code the packet was freed up before the function was called, so there was an attempt of freeing it up twice which when repeated several times lead to a SIGSEGV.

2016-09-14 15:27 UTC, mwiget commented
verified branch fix-crash-on-not-bound-ipv4-packet in my lab. Problem fixed.

2016-09-14 15:36 UTC, wingo commented on src/apps/lwaftr/lwaftr.lua
> +local debug = lib.getenv("LWAFTR_DEBUG") or false
remove "or false", it's not needed

2016-09-14 15:37 UTC, wingo commented on src/program/packetblaster/lwaftr/lwaftr.lua
> +   v4only       = "4",    -- generate only public IPv4 traffic
Unrelated; fine with me tho :)

2016-09-14 15:58 UTC, wingo commented on src/apps/lwaftr/lwaftr.lua
>        return transmit_icmpv4_reply(lwstate, reply, pkt)
This is not right.  After drop(pkt) you may not use pkt again, as you do here on line 715.

2016-09-14 16:09 UTC, wingo commented
As we were discussing on the channel, this bug was introduced in f78bd2072d8; cc @teknico.  It's a pretty classic mistake which we all have made :).  I think we need to be systematic about how we deallocate packets.  I kinda like the "transmit_reply(link, packet, orig_packet)" idiom because it centralizes ownership into that one function.  See commit 3bd50acf983599b1e086f9e7f392ef32bda67e58 for a related bug fix, only the other way (memory leaks instead of use-after-free).

Do you think it's possible instead to move the ICMPv4 accounting stuff into transmit_icmpv4_reply() instead and keep the orig_pkt argument in place?  We need to figure out good patterns for making sure we don't introduce this kind of bug again.  I am interested in your thoughts here :)

2016-09-14 16:19 UTC, dpino commented
@wingo: Agree, I like the idiom too. Moving `orig_pkt` out of `transmit_icmpv4_reply` was the simplest thing to do since deallocation of ipv4 packets was done differently, but definitely having a single place where the deallocation is done is a good idea, specially in the long run. I will rework the patch :)

2016-09-14 17:23 UTC, dpino commented
Redid patch. Moved deallocation of original packet to `transmit_icmpv4_reply`. If the packet has a source link defined `drop_ipv4` is used. If not the packet is deallocated with `drop` (for instance an IPv6 packet).`

2016-09-15 08:26 UTC, teknico requested changes
Yeah, double deallocation mistake, @kbara will also be interested.

However, rather than work around `drop_ipv4` we should change it instead. I'll send an alternative PR.

2016-09-15 09:00 UTC, teknico commented
Please see #440.

2016-09-15 09:13 UTC, teknico commented
Nope, #440 is sending both IPv4 and IPv6 packets to drop_ipv4 which is wrong. Sorry for the noise.

2016-09-15 09:14 UTC, teknico approved these changes

2016-09-16 05:54 UTC, kbara commented
This really proves what @teknico keeps saying about us needing better internal docs. I've systemized how packets are freed to avoid this kind of error during design, and then later design changes have broken it, perhaps because it's not documented.

I'm not thrilled with the mechanism of this patch - freeing or not depending on whether an optional third argument to a function is passed - but I'll LGTM it, since it gets rid of a serious bug.

2016-09-19 08:24 UTC, merged