Add support for identity and identityref
Igalia/snabbswitch pull request #822
Opened 2017-05-24 09:57 UTC by dpino

Fixes https://github.com/Igalia/snabb/issues/798

2017-05-25 10:25 UTC, wingo requested changes
Looks good; would you mind making the indicated changes?  Thanks!

2017-05-25 10:25 UTC, wingo commented on src/lib/yang/schema.lua
> +declare_initializer(
please make this one line

2017-05-25 10:25 UTC, wingo commented on src/lib/yang/schema.lua
> +   local function resolve_bases(bases, env)
Please add a comment: "Resolve argument of "base" statements to identity fqid and collect in a list."

2017-05-25 10:25 UTC, wingo commented on src/lib/yang/schema.lua
> +end
Add `lookup_identity = util.memoize(lookup_identity)` please.

2017-05-25 10:25 UTC, wingo commented on src/lib/yang/schema.lua
> +end
Likewise please memoize this function.

2017-05-25 10:25 UTC, wingo commented on src/lib/yang/value.lua
> +   return assert(str, 'missing value for '..what)
We should add a comment that these references are expanded in the validation phase.

2017-05-29 14:33 UTC, dpino commented on src/lib/yang/schema.lua
> +end
I don't know why this comment is not marked as outdated. The changes was addressed in the amend patch.

2017-05-29 14:33 UTC, dpino commented on src/lib/yang/schema.lua
> +end
Likewise this case.

2017-05-30 06:28 UTC, wingo approved these changes
thanks!

2017-05-30 08:37 UTC, merged