Add XPathPrinter
Igalia/snabbswitch pull request #843
Opened 2017-06-19 05:25 UTC by dpino

Fixed #837 . I'm not sure whether this is the best approach. Basically it transforms a standard output to an xpath output. 

The PR doesn't tackle Mislav's suggest to print out default values (this could be a different issue).

Example:

```
$ sudo ./snabb config get 2419 /softwire-config/external-interface
allow-incoming-icmp false;
error-rate-limiting {
  packets 600000;
}
generate-icmp-errors false;
ip 10.0.1.1;
mac 02:aa:aa:aa:aa:aa;
next-hop {
  mac 02:99:99:99:99:99;
}
reassembly {
  max-fragments-per-packet 40;
}
```

```bash
$ sudo ./snabb config get --xpath-format 2419 /softwire-config/external-interface                                                                    
/allow-incoming-icmp false
/error-rate-limiting/packets 600000
/generate-icmp-errors false
/ip 10.0.1.1
/mac 02:aa:aa:aa:aa:aa
/next-hop/mac 02:99:99:99:99:99
/reassembly/max-fragments-per-packet 40
```

2017-06-19 08:43 UTC, mislavn commented
Thank you @dpino.

@wingo is it possible to add a flag to snabb config so it shows the default values also?

2017-06-20 11:37 UTC, mislavn commented
@dpino can you also implement this for state data?

2017-06-22 14:23 UTC, dpino commented
@mislavn yep, no problem, I will send a new commit for get-state. Default variables is also doable. Andy and I discussed it offline and most likely we will add a knob to force print out of default variables (we think it's still valuable in some cases to not print out the defaults to reduce output size).

2017-06-22 14:31 UTC, dpino commented
xpath-format in get-state example:

```
$ sudo ./snabb config get-state --xpath-format 11973 /
/softwire-state/drop-all-ipv4-iface-bytes 0
/softwire-state/drop-all-ipv4-iface-packets 0
/softwire-state/drop-all-ipv6-iface-bytes 0
/softwire-state/drop-all-ipv6-iface-packets 0
/softwire-state/drop-bad-checksum-icmpv4-bytes 0
...
/softwire-state/out-ipv6-frag-not 0
/softwire-state/out-ipv6-packets 0
```

2017-06-22 16:03 UTC, dpino commented
Added a kbob to print out default values. Example:

**Run lwAFTR**

```bash
$ sudo ./snabb lwaftr run --name lwaftr --reconfigurable --conf lwaftr-migrated-2.conf --on-a-stick 82:00.1
```

**Query standard external-interface**

```bash
$ sudo ./snabb config get lwaftr /softwire-config/external-interface
allow-incoming-icmp false;
error-rate-limiting {
  packets 600000;
}
generate-icmp-errors false;
ip 10.0.1.1;
mac 02:aa:aa:aa:aa:aa;
next-hop {
  mac 02:99:99:99:99:99;
}
reassembly {
  max-fragments-per-packet 40;
}
```

**Query external-interface printing out default values**

```bash
$ sudo ./snabb config get --print-default lwaftr /softwire-config/external-interface
allow-incoming-icmp false;
error-rate-limiting {
  packets 600000;
  period 2;
}
generate-icmp-errors false;
ip 10.0.1.1;
mac 02:aa:aa:aa:aa:aa;
mtu 1460;
next-hop {
  mac 02:99:99:99:99:99;
}
reassembly {
  max-fragments-per-packet 40;
  max-packets 20000;
}
```

2017-06-27 12:34 UTC, wingo requested changes
For the future, I think this PR would have been better if it were just one of these two features.  That said, it's a good start.  Some changes requested for both features.

2017-06-27 12:34 UTC, wingo commented on src/apps/config/leader.lua
> +   data.print_default(print_default or false)
"print_default or false" is the same as "print_default", at least in a boolean context.

2017-06-27 12:34 UTC, wingo commented on src/lib/yang/data.lua
> +         if print_default() or str ~= production.default then
Here print_default() always returns a true value AFAIU -- it returns the function from line 808.  Anyway this doesn't look right to me: can you change instead to add a "print_default" option on line 707?  The idea being, you derive a printer from a grammar either with default-printing or without.  It's a property of the printer.  That way you can just check a simple variable in the scalar printer to know whether to print defaults or no.

2017-06-27 12:34 UTC, wingo commented on src/program/config/xpath_printer.lua
> +      elseif p:peep() == '{' then
This isn't going to work in general.  The format for the xpath has one component per tree, yes, but for lists for example you are going to have e.g. `/foo/bar[a=A][b=B]/qux'.  I think doing this transformation on the client side is the wrong thing; we need to tell the leader that we want output in xpath format and have it generate it, using a printer derived from the grammar.  That way we also avoid paging the whole thing into memory on the client side.

2017-06-27 16:02 UTC, dpino commented on src/apps/config/leader.lua
> +   data.print_default(print_default or false)
Right, but there's a chance that print_default is nil when launching `config get` or `config get-state` without --print-default knob. I can force print_default to be false by default though.

2017-06-28 11:21 UTC, dpino commented
Printing of default-values was refactored out from this PR and moved to https://github.com/Igalia/snabb/pull/850.

I reworked the whole code and implemented an XPath printer similar to the standard data_printer, as Andy suggested. It's still work in progress, although the example above is working OK. I'd need to think more about how to handle arrays, tables and other data types.

Example:

```
$ sudo ./snabb lwaftr run --reconfigurable --name lwaftr2 --conf lwaftr.conf --on-a-stick 82:00.0
```

```
$ sudo ./snabb config get --xpath-format lwaftr2 /softwire-config/external-interface
/softwire-config/external-interface/allow-incoming-icmp false;
/softwire-config/external-interface/error-rate-limiting/packets 600000;
/softwire-config/external-interface/ip 10.10.10.10;
/softwire-config/external-interface/mac 12:12:12:12:12:12;
/softwire-config/external-interface/next-hop/mac 68:68:68:68:68:68;
/softwire-config/external-interface/reassembly/max-fragments-per-packet 40;
```

2017-06-28 11:29 UTC, wingo commented on src/lib/yang/snabb-config-leader-v1.yang
> +      leaf xpath-format { type boolean; }
can this option be "format=xpath" with the default being "format=yang"

2017-06-28 11:30 UTC, wingo commented on src/program/config/README.md
> +$ sudo ./snabb config get --xpath-format lwaftr2 /softwire-config/external-interface
Likewise can the command-line argument be `--format=xpath`

2017-06-28 11:32 UTC, wingo commented
For me, generally looking good; need to change to correctly print xpath paths for lists (the key goes in the path)

2017-06-30 07:52 UTC, dpino commented
Binding-table example (XPath format):

```
$ sudo ./snabb config get --format=xpath lwaftr /softwire-config/binding-table                                                                                 
/softwire-config/binding-table/[ipv4=178.79.150.3;psid=4]/b4-ipv6 127:14:25:36:47:58:69:128;
/softwire-config/binding-table/[ipv4=178.79.150.3;psid=4]/br-address 1e:2:2:2:2:2:2:af;
/softwire-config/binding-table/[ipv4=178.79.150.3;psid=4]/psid-length 6;
/softwire-config/binding-table/[ipv4=178.79.150.233;psid=22788]/b4-ipv6 127:11:12:13:14:15:16:128;
/softwire-config/binding-table/[ipv4=178.79.150.233;psid=22788]/br-address 8:9:a:b:c:d:e:f;
/softwire-config/binding-table/[ipv4=178.79.150.233;psid=22788]/psid-length 16;
```

External-interface example (XPath format):

```
$ sudo ./snabb config get --format=xpath lwaftr /softwire-config/external-interface
/softwire-config/external-interface/allow-incoming-icmp false;
/softwire-config/external-interface/packets 600000;
/softwire-config/external-interface/ip 10.10.10.10;
/softwire-config/external-interface/mac 12:12:12:12:12:12;
/softwire-config/external-interface/mac 68:68:68:68:68:68;
/softwire-config/external-interface/max-fragments-per-packet 40;
```

2017-06-30 08:30 UTC, dpino commented
Fixed key composition in XPath format:

```
$ sudo ./snabb config get --format=xpath lwaftr /softwire-config/binding-table
/softwire-config/binding-table/softwire[ipv4=178.79.150.3][psid=4]/b4-ipv6 127:14:25:36:47:58:69:128;
/softwire-config/binding-table/softwire[ipv4=178.79.150.3][psid=4]/br-address 1e:2:2:2:2:2:2:af;
/softwire-config/binding-table/softwire[ipv4=178.79.150.3][psid=4]/psid-length 6;
/softwire-config/binding-table/softwire[ipv4=178.79.150.233][psid=22788]/b4-ipv6 127:11:12:13:14:15:16:128;
/softwire-config/binding-table/softwire[ipv4=178.79.150.233][psid=22788]/br-address 8:9:a:b:c:d:e:f;
/softwire-config/binding-table/softwire[ipv4=178.79.150.233][psid=22788]/psid-length 16;
/softwire-config/binding-table/softwire[ipv4=178.79.150.1][psid=0]/b4-ipv6 127:10:20:30:40:50:60:128;
/softwire-config/binding-table/softwire[ipv4=178.79.150.1][psid=0]/br-address 8:9:a:b:c:d:e:f;
/softwire-config/binding-table/softwire[ipv4=178.79.150.1][psid=0]/psid-length 0;
```

2017-06-30 12:21 UTC, wingo commented on src/lib/yang/data.lua
> +      local serialize = value_serializer(production.element_type)
I think this also needs additional work (should print as [position()=1] e.g.)

2017-06-30 16:39 UTC, dpino commented
Implemented support for printing out arrays in XPath format. There's currently no `leaf-list` elements in snabb-softwire-v2.yang, which are compiled to arrays. In order to test the implementation was working OK, I temporarily added a leaf-list to the schema.

```
     container external-interface {
       description
        "Configuration for the external, internet-facing IPv4
@@ -168,6 +167,10 @@ module snabb-softwire-v2 {
          "Maximum packet size to send on the IPv4 interface.";
       }

+      leaf-list public-ip {
+        type inet:ipv4-address;
+      }
+
       uses traffic-filters;
```

Example:

```
$ sudo ./snabb config get --format=xpath lwaftr2 /softwire-config/external-interface
/softwire-config/external-interface/allow-incoming-icmp false;
/softwire-config/external-interface/error-rate-limiting/packets 600000;
/softwire-config/external-interface/ip 10.10.10.10;
/softwire-config/external-interface/mac 12:12:12:12:12:12;
/softwire-config/external-interface/next-hop/mac 68:68:68:68:68:68;
/softwire-config/external-interface[position()=1]/public-ip 10.10.10.10;
/softwire-config/external-interface[position()=2]/public-ip 10.10.10.11;
/softwire-config/external-interface/reassembly/max-fragments-per-packet 40;
```

2017-07-04 13:17 UTC, dpino commented
Mislav informed me via private conversation semicolons are not needed. As for absolute and relative paths, there's no preference. I must said here that when directly querying a leaf, there's no attribute value printed, thus there's no absolute path. For instance:

```
sudo ./snabb config get --format=xpath lwaftr2 /softwire-config/external-interface/mac
12:12:12:12:12:12;
```

Is this consistent? Should we prefer relative paths instead?

2017-07-05 08:09 UTC, wingo commented
On Tue 04 Jul 2017 15:17, Diego Pino <notifications@github.com> writes:

> Mislav informed me via private conversation semicolons are not needed. As for absolute and relative paths, there's no preference. I must said here that when directly querying a leaf, there's no attribute value printed, thus there's no absolute path. For instance:
>
> sudo ./snabb config get --format=xpath lwaftr2 /softwire-config/external-interface/mac
> 12:12:12:12:12:12;
>
> Is this consistent? Should we prefer relative paths instead?

I think we should prepend the queried absolute path to all results, so
that all results have full paths.  Just MHO!

2017-07-05 15:32 UTC, dpino commented
@wingo: Sounds reasonable. So I will tackle those changes in a new set of commits (do not print semicolon and print absolute path for queries that only return data).

2017-07-06 11:34 UTC, dpino commented
I think is working fine now. Some examples:

```
$ sudo ./snabb config get --format=xpath lwaftr /softwire-config/binding-table/softwire[ipv4=178.79.150.2][psid=7850]/br-address
/softwire-config/binding-table/softwire[ipv4=178.79.150.2][psid=7850]/br-address 1e:1:1:1:1:1:1:af
```


```
$ sudo ./snabb config get --format=xpath lwaftr /softwire-config/binding-table
/softwire-config/binding-table/softwire[ipv4=178.79.150.3][psid=4]/b4-ipv6 127:14:25:36:47:58:69:128
/softwire-config/binding-table/softwire[ipv4=178.79.150.3][psid=4]/br-address 1e:2:2:2:2:2:2:af
/softwire-config/binding-table/softwire[ipv4=178.79.150.3][psid=4]/port-set/psid-length 6
/softwire-config/binding-table/softwire[ipv4=178.79.150.233][psid=22788]/b4-ipv6 127:11:12:13:14:15:16:128
/softwire-config/binding-table/softwire[ipv4=178.79.150.233][psid=22788]/br-address 8:9:a:b:c:d:e:f
/softwire-config/binding-table/softwire[ipv4=178.79.150.233][psid=22788]/port-set/psid-length 16
```

2017-07-06 12:10 UTC, wingo approved these changes
lgtm.  thanks for this!

2017-07-06 15:49 UTC, merged